version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\muesli\beehive

environment:
  GOPATH: c:\gopath
  GO111MODULE: on

install:
    - echo %PATH%
    - echo %GOPATH%
    - go version
    - go env
    - git submodule update --init
    - ps: |
        go.exe get -t -d (go.exe list ./... `
        |? { -not $_.Contains('/vendor/') })

build_script:
    - ps: |
        go.exe test -v -cpu=2 (go.exe list ./... `
        |? { -not $_.Contains('/vendor/') })
    - go build
