# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/ChimeraCoder/anaconda"
  version = "2.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/CleverbotIO/go-cleverbot.io"

[[constraint]]
  branch = "master"
  name = "github.com/MariaTerzieva/gotumblr"

[[constraint]]
  branch = "master"
  name = "github.com/Profpatsch/GoOse"

[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/akashshinde/go_cricket"

[[constraint]]
  name = "github.com/briandowns/openweathermap"
  version = "0.9.0"

[[constraint]]
  name = "github.com/carlosdp/twiliogo"
  version = "0.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/deckarep/gosx-notifier"

[[constraint]]
  name = "github.com/emicklei/go-restful"
  version = "2.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/fluffle/goirc"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  branch = "master"
  name = "github.com/glaxx/go_pastebin"

[[constraint]]
  name = "github.com/go-gomail/gomail"
  version = "2.0.0"

[[constraint]]
  name = "github.com/go-telegram-bot-api/telegram-bot-api"
  version = "4.6.1"

[[constraint]]
  name = "github.com/google/go-github"
  version = "15.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/guelfey/go.dbus"

[[constraint]]
  name = "github.com/huandu/facebook"
  version = "2.1.2"

[[constraint]]
  branch = "master"
  name = "github.com/huin/goserial"

[[constraint]]
  branch = "master"
  name = "github.com/jayeshsolanki93/devgorant"

[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  version = "0.0.9"

[[constraint]]
  branch = "master"
  name = "github.com/mattn/go-xmpp"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "4.0.8"

[[constraint]]
  branch = "master"
  name = "github.com/mnzt/tinder"

[[constraint]]
  branch = "master"
  name = "github.com/muesli/go.hue"

[[constraint]]
  branch = "master"
  name = "github.com/muesli/goefa"

[[constraint]]
  branch = "master"
  name = "github.com/muesli/smolder"

[[constraint]]
  name = "github.com/nlopes/slack"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[[constraint]]
  branch = "master"
  name = "github.com/odwrtw/transmission"

[[constraint]]
  name = "github.com/simplepush/simplepush-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.4"

[[constraint]]
  branch = "master"
  name = "github.com/sromku/go-gitter"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  branch = "master"
  name = "layeh.com/gumble"

[prune]
  go-tests = true
  unused-packages = true
